export const links = [
  { label: "Home", href: "/" },
  { label: "Find Jobs", href: "/jobs" },
  { label: "Candidates", href: "/candidates" },
  { label: "Blog", href: "/blog" },
  { label: "About Us", href: "/about-us" },
];

export const JobsData = [
  {
    icon: "/segment.webp",
    jobTitle: "Software Engineer (Android), Libraries",
    orgName: "Segment",
    location: "London, UK",
    createdAt: "11 hours ago",
    salaryRange: "$35k - $45k",
    jobType: ["Full Time", "Private", "Urgent"],
  },
  {
    icon: "/catalyst.webp",
    jobTitle: "Recruiting Coordinator",
    orgName: "Catalyst",
    location: "London, UK",
    createdAt: "11 hours ago",
    salaryRange: "$35k - $45k",
    jobType: ["Freelancer", "Private", "Urgent"],
  },
  {
    icon: "/invision.webp",
    jobTitle: "Product Manager, Studio",
    orgName: "Upwork",
    location: "London, UK",
    createdAt: "11 hours ago",
    salaryRange: "$35k - $45k",
    jobType: ["Temporary", "Private", "Urgent"],
  },
  {
    icon: "/up.webp",
    jobTitle: "Senior Product Designer",
    orgName: "Figma",
    location: "London, UK",
    createdAt: "11 hours ago",
    salaryRange: "$35k - $45k",
    jobType: ["Full Time", "Private", "Urgent"],
  },
  {
    icon: "/figma.webp",
    jobTitle: "Software Engineer (Android), Libraries",
    orgName: "Figma",
    location: "London, UK",
    createdAt: "11 hours ago",
    salaryRange: "$35k - $45k",
    jobType: ["Freelancer", "Private", "Urgent"],
  },
];


export const locations = [
  "Remote",
  "On-Site",
  "Hibrid",
];

export  const experienceLevels = [
  "Entry Level",
  "Mid Level",
  "Senior Level",
  "Director",
  "Executive",
];

export const skills = [
  "UI Design",
  "UX Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Prototyping",
  "User Research",
  "Design Systems",
  "HTML/CSS",
  "JavaScript",
  "React",
  "Product Design",
];

export const jobTypes = [
  "Full-time",
  "Part-time",
  "Contract",
  ];

export const JobsDataList = [
  {
    id: 1,
    title: "Design Intuitive UI for Enterprise Software",
    company: "TechCorp Inc.",
    logo: "...",
    position: "Senior UI Designer",
    location: "San Francisco, CA (Remote)",
    salary: "$120,000 - $150,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 5 days",
    skills: ["Figma", "UI Design", "Design Systems", "Prototyping"],
    postedDate: "2 days ago",
    description:
      "TechCorp Inc. is seeking a Senior UI Designer to lead design efforts for our enterprise-level web and desktop applications. You’ll be responsible for creating and maintaining scalable design systems, conducting usability testing, and partnering closely with Product and Engineering teams. Ideal candidates have a strong background in Figma, prototyping, and interaction patterns, with at least 5 years of experience in UI design. This is a 100% remote role with flexible hours.",
    matchPercentage: 95,
    type: ["Full Time", "Remote", "Private"],
    category: "Design",
  },
  {
    id: 2,
    title: "Drive Product Research at FinTech Leader",
    company: "FinEdge Solutions",
    logo: "...",
    position: "UX Researcher",
    location: "New York, NY (Hybrid)",
    salary: "$110,000 - $135,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 4 days",
    skills: ["User Research", "Usability Testing", "Data Analysis", "Interviewing"],
    postedDate: "3 days ago",
    description:
      "FinEdge Solutions is hiring a UX Researcher to lead research efforts shaping our next-generation financial tools. You’ll design and execute qualitative and quantitative studies including interviews, surveys, focus groups, and usability tests. Your insights will inform product features, roadmaps, and design decisions. The role includes close collaboration with Product, Design, Analytics, and Engineering teams. Hybrid role with 2 days/week in the NYC office.",
    matchPercentage: 88,
    type: ["Full Time", "Hybrid", "Urgent"],
    category: "Research",
  },
  {
    id: 3,
    title: "Design Creative Products for Global Brands",
    company: "CreativeX Studio",
    logo: "...",
    position: "Product Designer",
    location: "Los Angeles, CA (On-site)",
    salary: "$115,000 - $140,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 6 days",
    skills: ["UI/UX", "Product Thinking", "Wireframing", "Adobe Suite"],
    postedDate: "1 day ago",
    description:
      "CreativeX Studio is looking for a Product Designer to craft innovative solutions for top-tier global brands across web and mobile. Responsibilities include leading design sprints, creating wireframes and high-fidelity prototypes, conducting user testing, and delivering polished UI visuals using Adobe XD, Photoshop, and Illustrator. The ideal person embraces design thinking, product strategy, and cross-functional teamwork. Position is fully on-site in our vibrant LA headquarters.",
    matchPercentage: 92,
    type: ["Full Time", "Onsite"],
    category: "Design",
  },
  {
    id: 4,
    title: "Build UI/UX for B2B SaaS Platforms",
    company: "SoftMatrix Labs",
    logo: "...",
    position: "UI/UX Designer",
    location: "Austin, TX (Remote)",
    salary: "$100,000 - $130,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 2 days",
    skills: ["UI Design", "UX Design", "Sketch", "Figma"],
    postedDate: "5 days ago",
    description:
      "SoftMatrix Labs seeks a UI/UX Designer to build intuitive, accessible interfaces for SaaS solutions targeting enterprise clients. You will craft wireframes, interactive prototypes, and UI visuals using Sketch and Figma, ensuring consistency across components. The role includes conducting design reviews, collaborating with developers to ensure pixel-perfect implementation, and iterating based on user feedback. This remote role offers flexibility and autonomy.",
    matchPercentage: 85,
    type: ["Full Time", "Remote"],
    category: "Design",
  },
  {
    id: 5,
    title: "Design for E-Commerce & Branding Campaigns",
    company: "GlobalRetail Inc.",
    logo: "...",
    position: "Digital Designer",
    location: "Chicago, IL (Hybrid)",
    salary: "$90,000 - $115,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "expired",
    skills: ["UI Design", "Branding", "Illustration", "Typography"],
    postedDate: "1 week ago",
    description:
      "GlobalRetail Inc. is looking for a Digital Designer to create engaging visuals for e-commerce, online marketing, and brand campaigns. You’ll design landing pages, email templates, banners, and social media assets that align with brand guidelines. Strong skills in illustration, typography, and Adobe Creative Suite are essential. This is a hybrid role with office presence 2–3 days per week in Chicago; some part-time schedules are possible.",
    matchPercentage: 78,
    type: ["Part Time", "Hybrid"],
    category: "Marketing",
  },
  {
    id: 6,
    title: "Lead Product Design in a Fast-Paced Tech Team",
    company: "InnovateTech",
    logo: "...",
    position: "Senior Product Designer",
    location: "Seattle, WA (On-site)",
    salary: "$130,000 - $160,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 5 days",
    skills: ["Product Design", "UI/UX", "Design Leadership", "Design Thinking"],
    postedDate: "2 days ago",
    description:
      "InnovateTech is seeking a Senior Product Designer to drive end-to-end design for core product initiatives. You will mentor junior designers, facilitate design thinking workshops, contribute to product roadmaps, and own the look and feel of high-impact features. Expertise in Figma, UX research, and agile methodologies is required. The role is full-time and on-site at our flagship Seattle office.",
    matchPercentage: 91,
    type: ["Full Time", "Onsite"],
    category: "Design",
  },
  {
    id: 7,
    title: "Design Accessible Health Platforms Remotely",
    company: "HealthTech Solutions",
    logo: "...",
    position: "UX/UI Designer",
    location: "Boston, MA (Remote)",
    salary: "$105,000 - $135,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 3 days",
    skills: ["Healthcare UX", "UI Design", "Accessibility", "Figma"],
    postedDate: "4 days ago",
    description:
      "HealthTech Solutions is hiring a UX/UI Designer to deliver inclusive, accessible healthcare applications for providers and patients. You’ll wireframe, prototype, and design UI in Figma, ensuring compliance with WCAG standards. In this remote role, you’ll collaborate with clinicians, product managers, developers, and compliance teams to iterate designs based on user feedback and clinical requirements.",
    matchPercentage: 86,
    type: ["Full Time", "Remote"],
    category: "Healthcare",
  },
  {
    id: 8,
    title: "Design Learning Experiences for Global Students",
    company: "EduLearn",
    logo: "...",
    position: "Interaction Designer",
    location: "Remote",
    salary: "$95,000 - $120,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "expired",
    skills: ["Interaction Design", "Prototyping", "User Testing", "Educational UX"],
    postedDate: "1 week ago",
    description:
      "EduLearn is seeking an Interaction Designer to shape user journeys and interactive flows across its digital education platforms. You will develop interactive prototypes, conduct usability testing with students and instructors, and refine experiences based on feedback. Expertise in Figma, prototyping tools, and educational UX principles is required. Fully remote opportunity.",
    matchPercentage: 82,
    type: ["Full Time", "Remote", "Education"],
    category: "Education",
  },
  {
    id: 9,
    title: "Create Stunning Visuals for Streaming Platforms",
    company: "MediaStream",
    logo: "...",
    position: "Visual Designer",
    location: "Los Angeles, CA (Hybrid)",
    salary: "$100,000 - $125,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 4 days",
    skills: ["Visual Design", "Brand Design", "Motion Graphics", "Illustration"],
    postedDate: "3 days ago",
    description:
      "MediaStream is looking for a Visual Designer to develop brand-led imagery and motion graphics for its streaming platform. Responsibilities include creating key art, UI visuals, promotional banners, and animated social content. Proficiency in After Effects, Illustrator, and Photoshop is essential. Hybrid role based in Los Angeles with flexible in-office days.",
    matchPercentage: 79,
    type: ["Full Time", "Hybrid"],
    category: "Media",
  },
  {
    id: 10,
    title: "Design the Future of Automotive UX",
    company: "FutureMobility",
    logo: "...",
    position: "UX Designer",
    location: "Detroit, MI (On-site)",
    salary: "$110,000 - $140,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 2 days",
    skills: ["UX Design", "User Research", "Wireframing", "Prototyping"],
    postedDate: "5 days ago",
    description:
      "FutureMobility is hiring a UX Designer to define next-gen user experiences in connected vehicles and mobility apps. You’ll conduct user research, create detailed wireframes, high-fidelity prototypes, and iterate interfaces based on testing with drivers. Collaboration with engineers, product managers, and auto UX experts is key. Full-time, on-site role in Detroit.",
    matchPercentage: 84,
    type: ["Full Time", "Onsite", "Automotive"],
    category: "Automotive",
  },
  {
    id: 11,
    title: "Simplify Enterprise UX for Cloud Tools",
    company: "CloudSolutions",
    logo: "...",
    position: "Product Designer",
    location: "Remote",
    salary: "$115,000 - $145,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "in 5 days",
    skills: ["Product Design", "UI/UX", "Design Systems", "Figma"],
    postedDate: "2 days ago",
    description:
      "CloudSolutions is searching for a Product Designer to streamline UX in its large-scale cloud infrastructure platform. Your responsibilities include designing UI frameworks, conducting usability testing, mapping user flows, and producing design documentation. Work remotely with Product, Engineering, and DevOps teams to drive UX consistency and scalability.",
    matchPercentage: 90,
    type: ["Full Time", "Remote", "Cloud"],
    category: "Cloud Computing",
  },
  {
    id: 12,
    title: "Design Green Technology Interfaces with Impact",
    company: "EcoTech Innovations",
    logo: "...",
    position: "UX/UI Designer",
    location: "Portland, OR (Hybrid)",
    salary: "$95,000 - $125,000 / year",
    rate: "$15 - $25",
    weeklyHours: "24h",
    expirationDate: "expired",
    skills: ["UI Design", "UX Design", "Sustainable Design", "Figma"],
    postedDate: "1 week ago",
    description:
      "EcoTech Innovations seeks a UX/UI Designer passionate about sustainability to build intuitive interfaces for green tech applications. You will design dashboards, web experiences, and mobile views that promote eco-awareness and energy monitoring. Experience with Figma, user-centered design, and environmental themes is a plus. Hybrid role based in Portland.",
    matchPercentage: 83,
    type: ["Full Time", "Hybrid", "Sustainability"],
    category: "Sustainability",
  },
];



export const CompanyDetailList = [
  {
    company: "TechCorp Inc.",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "FinEdge Solutions",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "CreativeX Studio",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "SoftMatrix Labs",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "GlobalRetail Inc.",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "InnovateTech",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "HealthTech Solutions",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "EduLearn",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "MediaStream",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "FutureMobility",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "CloudSolutions",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
  {
    company: "EcoTech Innovations",
    industry: "Software",
    size: "501-1,000",
    founded: 2011,
    phone: "123 456 7890",
    email: "info@joio.com",
    location: "London, UK",
  },
];




export const AboutData = [
  {
    value: "4M",
    desc: "4 million daily active users"
  },
  {
    value: "12k",
    desc: "Over 12k open job positions"
  },
  {
    value: "20M",
    desc: "Over 20 million stories shared"
  }
];
